/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register as a donor or field worker */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Account created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with email + password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Authenticated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user?: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all schools */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of schools */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["School"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a school (admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SchoolInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["School"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schools/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single school with its spray reports */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description School plus embedded sprayReports */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SchoolWithReports"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Update a school (admin only) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SchoolInput"];
                };
            };
            responses: {
                /** @description Updated school */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["School"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spray-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List spray reports (filterable) */
        get: {
            parameters: {
                query?: {
                    school?: string;
                    worker?: string;
                    startDate?: string;
                    endDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of spray reports */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SprayReport"][];
                    };
                };
            };
        };
        put?: never;
        /** Submit a new spray report (field worker+) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SprayReportInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SprayReport"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spray-reports/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current worker's own reports */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of the caller's spray reports */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SprayReport"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donations/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a (mock) Stripe checkout session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CheckoutRequest"];
                };
            };
            responses: {
                /** @description Checkout session URL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            sessionUrl: string;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donations/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current donor's donations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of donations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Donation"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Homepage summary — schools + students + $ raised vs. 100k goal */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Summary stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SummaryStats"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Legacy dashboard impact counters */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Impact stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImpactStats"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schools as a GeoJSON FeatureCollection */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description FeatureCollection of schools */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MapFeatureCollection"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly spray activity timeline */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of monthly buckets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TimelinePoint"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an image to Cloudinary */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        image: string;
                    };
                };
            };
            responses: {
                /** @description Upload succeeded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            url: string;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
        };
        HealthResponse: {
            /** @example ok */
            status: string;
            /** @example v1 */
            version: string;
            /** Format: int64 */
            ts: number;
        };
        /** @enum {string} */
        UserRole: "donor" | "field_worker" | "admin" | "super_admin";
        User: {
            _id: string;
            name: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["UserRole"];
        };
        RegisterRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            /** @enum {string} */
            role: "donor" | "field_worker";
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthResponse: {
            token: string;
            user: components["schemas"]["User"];
        };
        /** @enum {string} */
        SchoolStatus: "pending" | "active" | "completed";
        GeoPoint: {
            /** @enum {string} */
            type: "Point";
            coordinates: number[];
        };
        School: {
            _id: string;
            name: string;
            district: string;
            location: components["schemas"]["GeoPoint"];
            totalRooms: number;
            studentCount: number;
            photos: string[];
            sponsor?: string | {
                name?: string;
                email?: string;
            } | null;
            status: components["schemas"]["SchoolStatus"];
            /** Format: date-time */
            lastSprayDate?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        SchoolInput: {
            name: string;
            district: string;
            location: components["schemas"]["GeoPoint"];
            totalRooms?: number;
            studentCount?: number;
        };
        SchoolWithReports: components["schemas"]["School"] & {
            sprayReports?: components["schemas"]["SprayReport"][];
        };
        SprayReport: {
            _id: string;
            school: string | {
                _id?: string;
                name?: string;
                district?: string;
            };
            worker: string | {
                _id?: string;
                name?: string;
            };
            /** Format: date-time */
            date: string;
            roomsSprayed: number;
            photos: string[];
            notes?: string;
            gpsCoords?: {
                lat?: number;
                lng?: number;
            };
            verified: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        SprayReportInput: {
            school: string;
            /** Format: date-time */
            date: string;
            roomsSprayed: number;
            photos?: string[];
            notes?: string;
            gpsCoords?: {
                lat?: number;
                lng?: number;
            };
        };
        /** @enum {string} */
        DonationStatus: "pending" | "completed" | "failed";
        Donation: {
            _id: string;
            donor?: string;
            school?: string | {
                _id?: string;
                name?: string;
                district?: string;
            } | null;
            /** @description Amount in cents */
            amount: number;
            currency?: string;
            stripePaymentId?: string;
            recurring?: boolean;
            status?: components["schemas"]["DonationStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        CheckoutRequest: {
            schoolId?: string | null;
            /** @description Amount in cents */
            amount: number;
            recurring?: boolean;
        };
        ImpactStats: {
            totalSchools: number;
            totalRoomsSprayed: number;
            totalStudentsProtected: number;
            totalSprayReports: number;
        };
        SummaryStats: {
            /** @description Number of schools with an IRS spray completed */
            schoolsProtected: number;
            /** @description Sum of studentCount across protected schools */
            studentsCovered: number;
            /** @description Completed donations sum, in whole dollars */
            dollarsRaised: number;
            /** @description Student protection goal (currently 100000) */
            goal: number;
            /**
             * Format: float
             * @description studentsCovered / goal, clamped to [0, 1]
             */
            progressPct: number;
            /** Format: date-time */
            updatedAt: string;
        };
        TimelinePoint: {
            /** @description YYYY-MM */
            month: string;
            roomsSprayed: number;
            reportsCount: number;
        };
        MapFeatureCollection: {
            /** @enum {string} */
            type: "FeatureCollection";
            features: components["schemas"]["MapFeature"][];
        };
        MapFeature: {
            /** @enum {string} */
            type: "Feature";
            geometry: components["schemas"]["GeoPoint"];
            properties: {
                _id: string;
                name: string;
                district: string;
                studentCount?: number;
                totalRooms?: number;
                status?: components["schemas"]["SchoolStatus"];
                /** Format: date-time */
                lastSprayDate?: string | null;
                totalSprayReports?: number;
                /** Format: uri */
                thumbnailUrl?: string | null;
            };
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication required or invalid */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authenticated but not authorized */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        IdParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
