import {
  ink,
  pilgrimOrange,
  pilgrimOrangeDeep,
  pilgrimGold,
  paper,
  paperSoft,
  paperDepth,
  border,
  mutedText,
  danger,
  warning,
  olive,
  white,
  successSurface,
  successText,
} from './pilgrimColors';

export const pilgrimTheme = {
  colors: {
    primary: pilgrimOrange,
    primaryDeep: pilgrimOrangeDeep,
    accent: pilgrimGold,
    olive,
    ink,
    text: ink,
    textMuted: mutedText,
    background: paper,
    backgroundSoft: paperSoft,
    backgroundDepth: paperDepth,
    surface: white,
    border,
    successSurface,
    successText,
    warningSurface: '#fff1df',
    warningText: warning,
    dangerSurface: '#fdecec',
    dangerText: danger,
    white,
  },
  radii: {
    sm: 10,
    md: 16,
    lg: 24,
    pill: 999,
  },
  spacing: {
    screen: 18,
    section: 18,
  },
  shadow: {
    card: {
      elevation: 3,
      shadowColor: '#2d2d2d',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.08,
      shadowRadius: 18,
    },
    soft: {
      elevation: 1,
      shadowColor: '#2d2d2d',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
    },
  },
};
